from utils.error_handler import log_exception
# 其他导入

@log_exception
async def explore_and_complete_tasks(self):
    """探索并完成任务"""
    # 方法实现

@log_exception
async def explore_task(self, task):
    """探索任务"""
    # 方法实现

# 其他方法
