from utils.error_handler import log_exception
# 其他导入

@log_exception
async def load_tasks(self):
    """加载任务"""
    # 方法实现

@log_exception
async def complete_task(self, task):
    """完成任务"""
    # 方法实现

# 其他方法
